name: learderboard
description: A leaderboard project for companies.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_auth: any
  cloud_firestore: any
  firebase_core: any
  firebase_storage: any
  firebase_messaging: any
  firebase_analytics: any
  provider: any
  http: any
  flutter_dotenv: any
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any
  lint: any
  pedantic: any
  dart_code_metrics: any

flutter:
  uses-material-design: true
  generate: true

scripts:
  analyze: dartanalyzer --fatal-infos --fatal-warnings .
  metrics: metrics lib
