"""Add phone column to User table

Revision ID: c5199d2e366c
Revises: e324801acd72
Create Date: 2024-07-02 11:32:43.979315

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5199d2e366c"
down_revision: Union[str, None] = "e324801acd72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone", sa.String(), nullable=True))
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.drop_column("users", "phone")
    # ### end Alembic commands ###
