// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuh3NY8yOqjzgmW_3HIJsmNvEkRbLl5R8',
    appId: '1:415240497803:web:ee35e65ba2e8aa6d6d828e',
    messagingSenderId: '415240497803',
    projectId: 'dadyfoot-331b9',
    authDomain: 'dadyfoot-331b9.firebaseapp.com',
    storageBucket: 'dadyfoot-331b9.appspot.com',
    measurementId: 'G-S4Y7ENHK6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRnV8CEnTwBRYUZ415g6e_kCuzXftW0hs',
    appId: '1:415240497803:android:694aa7d724bc57cf6d828e',
    messagingSenderId: '415240497803',
    projectId: 'dadyfoot-331b9',
    storageBucket: 'dadyfoot-331b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCo0hpjz0fdnVKr3nr2Og5dwQ1fuHZCrU',
    appId: '1:415240497803:ios:62bd69cc750e3bd56d828e',
    messagingSenderId: '415240497803',
    projectId: 'dadyfoot-331b9',
    storageBucket: 'dadyfoot-331b9.appspot.com',
    iosBundleId: 'com.example.leaderboardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCo0hpjz0fdnVKr3nr2Og5dwQ1fuHZCrU',
    appId: '1:415240497803:ios:62bd69cc750e3bd56d828e',
    messagingSenderId: '415240497803',
    projectId: 'dadyfoot-331b9',
    storageBucket: 'dadyfoot-331b9.appspot.com',
    iosBundleId: 'com.example.leaderboardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuh3NY8yOqjzgmW_3HIJsmNvEkRbLl5R8',
    appId: '1:415240497803:web:210d7f997f6e28626d828e',
    messagingSenderId: '415240497803',
    projectId: 'dadyfoot-331b9',
    authDomain: 'dadyfoot-331b9.firebaseapp.com',
    storageBucket: 'dadyfoot-331b9.appspot.com',
    measurementId: 'G-ZVXZQ97QKJ',
  );

}